dist: bionic
sudo: required

arch:
  - amd64
  - arm64

env:
  global:
    - DOCKER_CLI_EXPERIMENTAL=enabled
#  jobs:
#    - DOCKER_BUILD_PLATFORM=linux/amd64,linux/arm/v7,linux/arm64
#    - DOCKER_BUILD_PLATFORM=linux/arm/v7
#    - DOCKER_BUILD_PLATFORM=linux/arm64
#    - FOO=bar BAR=baz

# uname -m
#  aarch64
#  x86_64
#  armv7l
before_install:
  - uname -a
  - export ARCH=$([ $(uname -m) = "x86_64" ] && echo "amd64" || echo "arm64")
  - mkdir -p ~/.docker/cli-plugins/
  - wget -O ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-${ARCH}
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  - docker info
install:
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name xbuilder --use
  - docker buildx inspect --bootstrap

script: true
deploy:
  - provider: script
    script: bash .travis/docker-release.sh
    skip_cleanup: true
    on:
      repo: democratic-csi/democratic-csi
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^master|next$
  - provider: script
    script: bash .travis/docker-release.sh
    skip_cleanup: true
    on:
      repo: democratic-csi/democratic-csi
      tags: true
