dist: bionic
sudo: required

arch:
  - amd64
  - arm64

#env:
#  - DOCKER_BUILD_PLATFORM=linux/amd64,linux/arm/v7,linux/arm64
#  - DOCKER_BUILD_PLATFORM=linux/arm/v7
#  - DOCKER_BUILD_PLATFORM=linux/arm64
#  - FOO=bar BAR=baz

before_install:
  - uname -a
  - curl -fsSL https://get.docker.com | sh
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - sudo service docker start
  - docker info
install:
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name xbuilder --use
  - docker buildx inspect --bootstrap

script: true
deploy:
  - provider: script
    script: bash .travis/docker-release.sh
    skip_cleanup: true
    on:
      repo: democratic-csi/democratic-csi
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^master|next$
  - provider: script
    script: bash .travis/docker-release.sh
    skip_cleanup: true
    on:
      repo: democratic-csi/democratic-csi
      tags: true
